### ISSUE TITLE
support for Pyodide 0.26.x

### ISSUE THREAD

**Issue by mscolnick** [duckdb/duckdb-pyodide#3]
First off, I want to say thank you! I have this running in [marimo](https://github.com/marimo-team/marimo)[1].

It works for Pyodide 0.25.x, but none of the current wheels seems to support 0.26.x. I am getting this error, when trying to install with micropip:

```python
 await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 66, in add_requirement
    check_compatible(wheel.filename)
  File "/lib/python3.12/site-packages/micropip/_utils.py", line 167, in check_compatible
    raise ValueError(
ValueError: Wheel was built with Emscripten v3.1.46 but Pyodide was built with Emscripten v3.1.58
```

[1] ![Screenshot 2024-07-11 at 4 00 01 PM](https://github.com/duckdb/duckdb-pyodide/assets/2753772/76c66f8e-a481-4d20-aefa-39285fbddedc)

**Comment by carlopi** [comment]
PR allowing this is https://github.com/duckdb/duckdb/pull/12965, plus build would need to be triggered manually.

**Comment by carlopi** [comment]
I have also updated the list of available wheels:
DuckDB v1.0.0 is packaged for Python 3.10, 3.11 and 3.12 (= Pyodide 0.26.1)

Thanks for raising this

**Comment by mscolnick** [comment]
Thanks for the quick turnaround!

**Comment by carlopi** [comment]
Connected: I was looking at https://github.com/pyodide/pyodide/pull/4684, that would also be great to have, and saw someone mentioned marimo in the PR, do you have by any chance ideas on how to progress there ?

**Comment by mscolnick** [comment]
It sounded like it was blocked on CI passing, but from some semi unrelated changes. 

We are just interested/excited in getting the Pyodide build supported since we have features that get enabled when duckdb is installed.
